#include "dashboard.h"

/* Dashboard HTML embebido — auto-refresca cada segundo via fetch() */
static const char DASHBOARD_HTML[] =
"<!DOCTYPE html>\n"
"<html lang=\"es\">\n"
"<head>\n"
"<meta charset=\"utf-8\">\n"
"<title>perfanalyzer dashboard</title>\n"
"<style>\n"
"  * { box-sizing: border-box; margin: 0; padding: 0; }\n"
"  body { background: #0d1117; color: #e6edf3; font-family: 'Segoe UI', monospace; }\n"
"  header { background: #161b22; padding: 1rem 2rem; border-bottom: 1px solid #30363d;\n"
"           display: flex; align-items: center; gap: 1rem; }\n"
"  header h1 { font-size: 1.3rem; color: #58a6ff; }\n"
"  #status-dot { width: 10px; height: 10px; border-radius: 50%; background: #3fb950; }\n"
"  #status-dot.error { background: #f85149; }\n"
"  .grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(220px, 1fr));\n"
"          gap: 1rem; padding: 1.5rem; }\n"
"  .card { background: #161b22; border: 1px solid #30363d; border-radius: 8px;\n"
"          padding: 1.2rem; }\n"
"  .card h3 { font-size: 0.75rem; color: #8b949e; text-transform: uppercase;\n"
"             letter-spacing: 1px; margin-bottom: 0.5rem; }\n"
"  .card .val { font-size: 2rem; font-weight: 700; color: #58a6ff; }\n"
"  .card .unit { font-size: 0.85rem; color: #8b949e; margin-left: 4px; }\n"
"  .card .bar-wrap { background: #21262d; border-radius: 4px; height: 8px;\n"
"                    margin-top: 0.6rem; overflow: hidden; }\n"
"  .card .bar { height: 100%; border-radius: 4px; transition: width 0.4s ease; }\n"
"  .bar-cpu  { background: #58a6ff; }\n"
"  .bar-mem  { background: #3fb950; }\n"
"  .bar-io   { background: #d2a8ff; }\n"
"  #chart-section { padding: 0 1.5rem 1.5rem; }\n"
"  #chart-section h2 { color: #8b949e; font-size: 0.85rem; text-transform: uppercase;\n"
"                      margin-bottom: 0.5rem; letter-spacing: 1px; }\n"
"  canvas { background: #161b22; border: 1px solid #30363d; border-radius: 8px;\n"
"           width: 100%; height: 180px; }\n"
"  #probes-section { padding: 0 1.5rem 2rem; }\n"
"  #probes-section h2 { color: #8b949e; font-size: 0.85rem; text-transform: uppercase;\n"
"                       margin-bottom: 0.8rem; letter-spacing: 1px; }\n"
"  table { width: 100%; border-collapse: collapse; font-size: 0.85rem; }\n"
"  th { text-align: left; color: #8b949e; padding: 0.4rem 0.6rem;\n"
"       border-bottom: 1px solid #30363d; }\n"
"  td { padding: 0.4rem 0.6rem; border-bottom: 1px solid #21262d; }\n"
"  tr:hover td { background: #21262d; }\n"
"  .ts { color: #8b949e; font-size: 0.75rem; }\n"
"  #no-probes { color: #8b949e; font-size: 0.85rem; font-style: italic; padding: 0.5rem 0; }\n"
"</style>\n"
"</head>\n"
"<body>\n"
"<header>\n"
"  <div id=\"status-dot\"></div>\n"
"  <h1>perfanalyzer</h1>\n"
"  <span id=\"ts-label\" class=\"ts\"></span>\n"
"  <span style=\"margin-left:auto;color:#8b949e;font-size:0.8rem\">"
"    Actualizando cada 1 s</span>\n"
"</header>\n"
"\n"
"<div class=\"grid\">\n"
"  <div class=\"card\">\n"
"    <h3>CPU Proceso</h3>\n"
"    <span class=\"val\" id=\"cpu-val\">--</span><span class=\"unit\">%</span>\n"
"    <div class=\"bar-wrap\"><div class=\"bar bar-cpu\" id=\"bar-cpu\" style=\"width:0\"></div></div>\n"
"  </div>\n"
"  <div class=\"card\">\n"
"    <h3>CPU Sistema</h3>\n"
"    <span class=\"val\" id=\"cpusys-val\">--</span><span class=\"unit\">%</span>\n"
"    <div class=\"bar-wrap\"><div class=\"bar bar-cpu\" id=\"bar-cpusys\" style=\"width:0\"></div></div>\n"
"  </div>\n"
"  <div class=\"card\">\n"
"    <h3>RSS (Memoria)</h3>\n"
"    <span class=\"val\" id=\"rss-val\">--</span><span class=\"unit\">MB</span>\n"
"    <div class=\"bar-wrap\"><div class=\"bar bar-mem\" id=\"bar-rss\" style=\"width:0\"></div></div>\n"
"  </div>\n"
"  <div class=\"card\">\n"
"    <h3>Memoria Peak</h3>\n"
"    <span class=\"val\" id=\"peak-val\">--</span><span class=\"unit\">MB</span>\n"
"    <div class=\"bar-wrap\"><div class=\"bar bar-mem\" style=\"width:100%\"></div></div>\n"
"  </div>\n"
"  <div class=\"card\">\n"
"    <h3>I/O Leídos</h3>\n"
"    <span class=\"val\" id=\"ior-val\">--</span><span class=\"unit\">MB</span>\n"
"    <div class=\"bar-wrap\"><div class=\"bar bar-io\" id=\"bar-ior\" style=\"width:0\"></div></div>\n"
"  </div>\n"
"  <div class=\"card\">\n"
"    <h3>I/O Escritos</h3>\n"
"    <span class=\"val\" id=\"iow-val\">--</span><span class=\"unit\">MB</span>\n"
"    <div class=\"bar-wrap\"><div class=\"bar bar-io\" id=\"bar-iow\" style=\"width:0\"></div></div>\n"
"  </div>\n"
"  <div class=\"card\">\n"
"    <h3>cgroup CPU</h3>\n"
"    <span class=\"val\" id=\"cgcpu-val\">--</span><span class=\"unit\">ms</span>\n"
"    <div class=\"bar-wrap\"><div class=\"bar bar-cpu\" id=\"bar-cgcpu\" style=\"width:0\"></div></div>\n"
"  </div>\n"
"  <div class=\"card\">\n"
"    <h3>cgroup Memoria</h3>\n"
"    <span class=\"val\" id=\"cgmem-val\">--</span><span class=\"unit\">MB</span>\n"
"    <div class=\"bar-wrap\"><div class=\"bar bar-mem\" id=\"bar-cgmem\" style=\"width:0\"></div></div>\n"
"  </div>\n"
"</div>\n"
"\n"
"<div id=\"chart-section\">\n"
"  <h2>CPU % — últimos 60 s</h2>\n"
"  <canvas id=\"cpu-chart\" width=\"1200\" height=\"180\"></canvas>\n"
"</div>\n"
"\n"
"<div id=\"probes-section\">\n"
"  <h2>Profiling por función</h2>\n"
"  <div id=\"probes-container\"><p id=\"no-probes\">Sin sondas registradas.</p></div>\n"
"</div>\n"
"\n"
"<script>\n"
"const MAX_POINTS = 60;\n"
"const cpuHistory = [];\n"
"\n"
"function fmt(v, decimals=1) {\n"
"  if (v == null || v < 0) return '--';\n"
"  return v.toFixed(decimals);\n"
"}\n"
"\n"
"function clamp(v, lo, hi) { return Math.max(lo, Math.min(hi, v)); }\n"
"\n"
"function barPct(v, max) {\n"
"  if (v == null || v < 0 || max <= 0) return '0%';\n"
"  return clamp(v / max * 100, 0, 100).toFixed(1) + '%';\n"
"}\n"
"\n"
"function drawChart() {\n"
"  const canvas = document.getElementById('cpu-chart');\n"
"  const ctx = canvas.getContext('2d');\n"
"  const W = canvas.offsetWidth  || 1200;\n"
"  const H = canvas.offsetHeight || 180;\n"
"  canvas.width  = W;\n"
"  canvas.height = H;\n"
"\n"
"  ctx.clearRect(0, 0, W, H);\n"
"  ctx.fillStyle = '#161b22';\n"
"  ctx.fillRect(0, 0, W, H);\n"
"\n"
"  if (cpuHistory.length < 2) return;\n"
"\n"
"  const pad = { t: 10, r: 10, b: 20, l: 40 };\n"
"  const w = W - pad.l - pad.r;\n"
"  const h = H - pad.t - pad.b;\n"
"\n"
"  /* Grid */\n"
"  ctx.strokeStyle = '#21262d';\n"
"  ctx.lineWidth = 1;\n"
"  for (let pct of [25, 50, 75, 100]) {\n"
"    const y = pad.t + h * (1 - pct / 100);\n"
"    ctx.beginPath(); ctx.moveTo(pad.l, y); ctx.lineTo(pad.l + w, y); ctx.stroke();\n"
"    ctx.fillStyle = '#8b949e'; ctx.font = '10px monospace';\n"
"    ctx.fillText(pct + '%', 2, y + 3);\n"
"  }\n"
"\n"
"  /* Línea CPU proceso */\n"
"  ctx.strokeStyle = '#58a6ff'; ctx.lineWidth = 2;\n"
"  ctx.beginPath();\n"
"  const step = w / (MAX_POINTS - 1);\n"
"  cpuHistory.forEach((v, i) => {\n"
"    const x = pad.l + i * step;\n"
"    const y = pad.t + h * (1 - clamp(v, 0, 100) / 100);\n"
"    i === 0 ? ctx.moveTo(x, y) : ctx.lineTo(x, y);\n"
"  });\n"
"  ctx.stroke();\n"
"}\n"
"\n"
"function renderProbes(probes) {\n"
"  const container = document.getElementById('probes-container');\n"
"  if (!probes || probes.length === 0) {\n"
"    container.innerHTML = '<p id=\"no-probes\">Sin sondas registradas.</p>';\n"
"    return;\n"
"  }\n"
"  let html = '<table><thead><tr>'\n"
"    + '<th>Función</th><th>Llamadas</th>'\n"
"    + '<th>Avg (µs)</th><th>Min (µs)</th><th>Max (µs)</th>'\n"
"    + '<th>p50 (µs)</th><th>p95 (µs)</th><th>p99 (µs)</th>'\n"
"    + '<th>CPU avg (µs)</th><th>ΔRSS avg (kB)</th>'\n"
"    + '</tr></thead><tbody>';\n"
"  for (const p of probes) {\n"
"    html += `<tr>\n"
"      <td><code>${p.name}</code></td>\n"
"      <td>${p.count}</td>\n"
"      <td>${fmt(p.elapsed_us_avg)}</td>\n"
"      <td>${fmt(p.elapsed_us_min)}</td>\n"
"      <td>${fmt(p.elapsed_us_max)}</td>\n"
"      <td>${fmt(p.elapsed_us_p50)}</td>\n"
"      <td>${fmt(p.elapsed_us_p95)}</td>\n"
"      <td>${fmt(p.elapsed_us_p99)}</td>\n"
"      <td>${fmt(p.cpu_us_avg)}</td>\n"
"      <td>${fmt(p.mem_delta_kb_avg, 1)}</td>\n"
"    </tr>`;\n"
"  }\n"
"  html += '</tbody></table>';\n"
"  container.innerHTML = html;\n"
"}\n"
"\n"
"async function refresh() {\n"
"  const dot = document.getElementById('status-dot');\n"
"  try {\n"
"    const [snapRes, probesRes] = await Promise.all([\n"
"      fetch('/snapshot'),\n"
"      fetch('/probes'),\n"
"    ]);\n"
"    const s = await snapRes.json();\n"
"    const probes = await probesRes.json();\n"
"\n"
"    dot.className = '';\n"
"\n"
"    const ts = new Date(s.ts_sec * 1000);\n"
"    document.getElementById('ts-label').textContent =\n"
"      ts.toLocaleTimeString();\n"
"\n"
"    const cpu = s.cpu_pct >= 0 ? s.cpu_pct : 0;\n"
"    const cpuSys = s.cpu_sys_pct >= 0 ? s.cpu_sys_pct : 0;\n"
"    const rssMB  = s.mem_rss_kb  / 1024;\n"
"    const peakMB = s.mem_peak_kb / 1024;\n"
"    const iorMB  = s.io_read_bytes  / (1024*1024);\n"
"    const iowMB  = s.io_write_bytes / (1024*1024);\n"
"    const cgcpuMs = s.cg_cpu_usage_us / 1000;\n"
"    const cgmemMB = s.cg_mem_current  / (1024*1024);\n"
"\n"
"    document.getElementById('cpu-val').textContent    = fmt(cpu);\n"
"    document.getElementById('cpusys-val').textContent = fmt(cpuSys);\n"
"    document.getElementById('rss-val').textContent    = fmt(rssMB);\n"
"    document.getElementById('peak-val').textContent   = fmt(peakMB);\n"
"    document.getElementById('ior-val').textContent    = fmt(iorMB);\n"
"    document.getElementById('iow-val').textContent    = fmt(iowMB);\n"
"    document.getElementById('cgcpu-val').textContent  = fmt(cgcpuMs, 0);\n"
"    document.getElementById('cgmem-val').textContent  = fmt(cgmemMB);\n"
"\n"
"    document.getElementById('bar-cpu').style.width    = barPct(cpu, 100);\n"
"    document.getElementById('bar-cpusys').style.width = barPct(cpuSys, 100);\n"
"    document.getElementById('bar-rss').style.width    = barPct(rssMB, peakMB || rssMB || 1);\n"
"    document.getElementById('bar-ior').style.width    = barPct(iorMB, Math.max(iorMB, iowMB) || 1);\n"
"    document.getElementById('bar-iow').style.width    = barPct(iowMB, Math.max(iorMB, iowMB) || 1);\n"
"    document.getElementById('bar-cgcpu').style.width  = barPct(cgcpuMs, cgcpuMs || 1);\n"
"    document.getElementById('bar-cgmem').style.width  = barPct(cgmemMB, peakMB || cgmemMB || 1);\n"
"\n"
"    cpuHistory.push(cpu);\n"
"    if (cpuHistory.length > MAX_POINTS) cpuHistory.shift();\n"
"    drawChart();\n"
"\n"
"    renderProbes(Array.isArray(probes) ? probes : []);\n"
"\n"
"  } catch (e) {\n"
"    dot.className = 'error';\n"
"  }\n"
"}\n"
"\n"
"refresh();\n"
"setInterval(refresh, 1000);\n"
"window.addEventListener('resize', drawChart);\n"
"</script>\n"
"</body>\n"
"</html>\n";

const char *dashboard_html(void) { return DASHBOARD_HTML; }
